server.port=8081
  
  # Kafka config
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
  
  # Custom Kafka topic
kafka.topic=sum-topic

# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/sumdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

configuration.service.url=http://property-service:8084
configuration.api.path=/api/properties/{key}

# Cache expiration time in minutes
cache.expiration-time=30