server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/sumdb
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka Consumer
kafka.consumer.bootstrap-servers=kafka:9092
kafka.consumer.group-id=sum-group
kafka.consumer.auto-offset-reset=earliest
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
kafka.consumer.properties.spring.json.trusted.packages=*

# Custom Kafka topic
kafka.topic=sum-topic
